#!/usr/bin/env python
from scapy.utils import PcapReader, PcapWriter
import gzip,zlib,cPickle
import scapy
from scapy.all import *
#a=rdpcap('pdf.pcap')
a=rdpcap(sys.argv[1])
#filename="pcapanalysis.log"
def analsys():
	#writer = PcapWriter(filename, append = True)
	for p in a:
		p.show()
		print "+"*88
if __name__ == '__main__':

	analsys()
